server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 200M
    storageClass: "oci-bv"
    accessMode: ReadWriteOnce
    annotations:
      volumeName: vault-pv
      volumeMounts:
        - name: vault-pv
      mountPath: /vault/data

ui:
  enabled: true
  serviceType: ClusterIP
