server:
  standalone:
    enabled: true
    config: |
      ui = true

      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      storage "file" {
        path = "/vault/data"
      }

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 200M
    storageClassName: oci-bv
    accessMode: ReadWriteOnce
    volumeName: "vault-pv"
    annotations: 
      volumeName: vault-pv
      storageClassName: oci-bv

ui:
  enabled: true
  serviceType: ClusterIP
