apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://kubernetes-sigs.github.io/nfs-ganesha-server-and-external-provisioner/
    chart: nfs-server-provisioner
    targetRevision: "1.8.0"
    helm:
      valuesObject:
        persistence:
          enabled: true
          storageClass: "local-path"
          size: 200Gi
        storageClass:
          name: nfs-client
          defaultClass: true
        nodeSelector:
          master: true
  destination:
    server: https://kubernetes.default.svc
    namespace: nfs
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
