apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.28.1"
    helm:
      valuesObject:
        server:
          standalone:
            enabled: true
            config: |
              ui = true
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              storage "file" {
                path = "/vault/data"
              }
          service:
            enabled: true
          dataStorage:
            enabled: false
          ingress:
            enabled: true
            annotations:
              kubernetes.io/ingress.class: "nginx"
              cert-manager.io/cluster-issuer: letsencrypt-prod
              nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
            ingressClassName: "nginx"
            pathType: Prefix
            activeService: true
            hosts:
              - host: vault.rabarbra.me
                paths:
                  - /
            tls:
              - secretName: vault-tls
                hosts:
                  - vault.rabarbra.me
        ui:
          enabled: true
          serviceType: ClusterIP
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
