apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: all-apps-infra
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rabarbra/k8s-argo-infra.git
    targetRevision: HEAD
    path: appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    # automated: 
    #   prune: true 
    #   selfHeal: true
