apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portainer
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://portainer.github.io/k8s/
    chart: portainer
    targetRevision: "1.0.57"
    helm:
      valuesObject:
        service:
          type: ClusterIP
        ingress:
          enabled: true
          ingressClassName: "nginx"
          annotations:
            kubernetes.io/ingress.class: "nginx"
            cert-manager.io/cluster-issuer: letsencrypt-prod
            nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
          hosts:
            - host: portainer.rabarbra.me
              paths:
                - path: "/"
          tls:
            - secretName: portainer-tls
              hosts:
                - portainer.rabarbra.me
          persistence:
            enabled: true
            size: "10Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: portainer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
