apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vault
spec:
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
        - "ReadWriteOnce"
      resources:
        requests:
          storage: 200M
        storageClassName: ""
        volumeName: vault-pv

