apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "33.0.0"
    helm:
      valuesObject:
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
          kubernetesGateway:
            enabled: false
        # certificatesResolvers:
        #   cloudflare:
        #     acme:
        #       email: rabarbrablad@gmail.com
        #       storage: acme.json
        #       dnschallenge:
        #         provider: cloudflare
        #         resolvers: 1.1.1.1
        # env:
        #   - name: CF_API_EMAIL
        #     valueFrom:
        #       secretKeyRef:
        #         key: email
        #         name: cloudflare-api-credentials
        #   - name: CF_API_KEY
        #     valueFrom:
        #       secretKeyRef:
        #         key: apiKey
        #         name: cloudflare-api-credentials
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
