apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://traefik.github.io/charts
    chart: traefik
    targetRevision: "33.0.0"
    helm:
      valuesObject:
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
          kubernetesGateway:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
