apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
spec:
  project: infra
  sources:
  - repoURL: https://dirsigler.github.io/uptime-kuma-helm
    chart: uptime-kuma
    targetRevision: "2.20.0"
    helm:
      valuesObject:
        nodeSelector:
          node-role.kubernetes.io/master: "true"
        ingress:
          enabled: true
          ingressClassName: "contour"
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt-prod
            ingress.kubernetes.io/force-ssl-redirect: "true"
            kubernetes.io/tls-acme: "true"
            projectcontour.io/websocket-routes: "/"
            # kubernetes.io/ingress.class: "nginx"
            # nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
            # nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
            # nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
            # nginx.ingress.kubernetes.io/server-snippets: |
            #   location / {
            #     proxy_set_header Upgrade $http_upgrade;
            #     proxy_http_version 1.1;
            #     proxy_set_header X-Forwarded-Host $http_host;
            #     proxy_set_header X-Forwarded-Proto $scheme;
            #     proxy_set_header X-Forwarded-For $remote_addr;
            #     proxy_set_header Host $host;
            #     proxy_set_header Connection "upgrade";
            #     proxy_set_header X-Real-IP $remote_addr;
            #     proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            #     proxy_set_header   Upgrade $http_upgrade;
            #     proxy_cache_bypass $http_upgrade;
            #   }
          hosts:
            - host: uptime.rabarbra.me
              paths:
                - path: "/"
                  pathType: ImplementationSpecific
          tls:
            - secretName: uptime-kuma-tls
              hosts:
                - uptime.rabarbra.me
        volume:
          enabled: true
          accessMode: ReadWriteOnce
          storageClass: "local-path"
          size: 200Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: uptime-kuma
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle
