apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/rabarbra/k8s-argo-infra.git
    targetRevision: HEAD
    path: apps/vault/base  # Specify the path to the application YAML if needed
    helm:
      chart: vault
      repoURL: https://helm.releases.hashicorp.com
      targetRevision: "0.28.0"
      valueFiles:
        - apps/vault/envs/prod/values-prod.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle

