apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://helm.releases.hashicorp.com
    chart: vault
    targetRevision: "0.28.0"
    helm:
      valueFiles:
        - $values/apps/vault/envs/prod/values-prod.yml
  - repoURL: https://github.com/rabarbra/k8s-argo-infra.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  ignoreDifferences:
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jqPathExpressions:
    - .webhooks[]?.clientConfig.caBundle

